//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace дэ2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int id_account { get; set; }
        public string Login_ { get; set; }
        public string Password_ { get; set; }
        public Nullable<int> id_role { get; set; }
    
        public virtual Role_ Role_ { get; set; }
    }
}
