//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace дэ2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int id { get; set; }
        public Nullable<int> child_id { get; set; }
        public Nullable<int> activity_schedule_id { get; set; }
        public Nullable<int> date_id { get; set; }
    
        public virtual Activity_Schedule Activity_Schedule { get; set; }
        public virtual Children Children { get; set; }
        public virtual Date_Of_Enrolment Date_Of_Enrolment { get; set; }
    }
}
