//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace дэ2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int request_id { get; set; }
        public Nullable<int> children_id { get; set; }
        public Nullable<int> parents_id { get; set; }
        public Nullable<int> parent_contact_id { get; set; }
        public Nullable<int> enrollment_date_id { get; set; }
        public Nullable<int> activities_id { get; set; }
    
        public virtual Activities Activities { get; set; }
        public virtual Children Children { get; set; }
        public virtual Date_Of_Enrolment Date_Of_Enrolment { get; set; }
        public virtual Parent_contacts Parent_contacts { get; set; }
        public virtual Parents Parents { get; set; }
    }
}
